repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^(backups/|.*backup.*/)
    -   id: end-of-file-fixer
        exclude: ^(backups/|.*backup.*/)

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        # Use .ruff.toml for configuration
    -   id: ruff-format
        # Use .ruff.toml for configuration
