repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

# Temporarily disable pyright until the codebase is more complete
# -   repo: local
#     hooks:
#     -   id: pyright
#         name: pyright
#         entry: pyright
#         language: system
#         types: [python]
#         pass_filenames: false
